language: c
os: linux
dist: bionic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8

  apt:
    - libcurl4-openssl-dev
    - jq

compiler:
  - gcc

script:
  - make
  - ./test.sh
